apiVersion: v1
kind: Service
metadata:
  labels:
    component: {{appName}}
    environment: {{env}}
  name: {{appName}}
spec:
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: {{appName}}