apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq-{{artifactid}}
  name: rabbitmq-{{artifactid}}-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq-{{artifactid}}
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq-{{artifactid}}
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m